services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./backend:./backend
    depends_on:
      - db
    networks:
      - auth_network
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./frontend:./frontend
    depends_on:
      - db
      - backend
    networks:
      - auth_network
  db:
    image: postgres
    port:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    networks:
      - auth_network
  pgadmin:
    image: pgadmin4
    ports:
      - "5050:80"
    networks:
      - auth_network
volumes:
  auth_data:

networks:
  auth_network:
    drive: bridge
